### ISSUE TITLE
Incorrect jQuery reference in settings view

### ISSUE THREAD

**Issue by raamssundar** [kunaldeo/django-livesettings3#1]
Getting the following error in `settings` view

```js
Failed to load resource: the server responded with a status of 404 (OK)
jquery.init.js:8 Uncaught ReferenceError: jQuery is not defined
```

**Comment by kunaldeo** [comment]
https://github.com/kunaldeo/django-livesettings3/commit/2514f375fa038d412392f77bbb2dc2a5913463e4 Fixed. Thanks for reporting it.

**Comment by kunaldeo** [comment]
Fixed by https://github.com/kunaldeo/django-livesettings3/commit/2514f375fa038d412392f77bbb2dc2a5913463e4
