### ISSUE TITLE
Livesettings doesn't cache for values not stored in the db

### ISSUE THREAD

**Issue by pjrobertson** [kunaldeo/django-livesettings3#17]
Steps to reproduce:

1. Set up some livesettings with `config_register`
2. Make sure to set 'default' values in `config_register`. E.g.:
```
...
MYAPP_GROUP = ConfigurationGroup('MyApp', _('My App Settings'), ordering=0)
config_register(
        DecimalValue(
                MYAPP_GROUP,
                'ELECTRICITY_COST',
                description="Electricity cost ($)",
                default=1
                help_text="The cost of electricity per kwh"
                )
        )
```
3. Run django and confirm that the setting does not exist in the db:
```
select * from livesettings_setting;
# should be empty
```
4. Now, run a method that access the setting multiple times in your view:
```
for i in range(0,1000):
    config_value('MyApp' 'ELECTRICITY_COST')
```
5. Note how livesettings hits the DB every time to try and access the setting, however since the setting doesn't exist in the DB, `find_setting()` raises a `SettingNotSet` and then `_value()` [here](https://github.com/kunaldeo/django-livesettings3/blob/76394219b6a8d022f5825683f1f00682b3f161ec/livesettings/values.py#L442) falls back to getting the default value.

**Expected Behaviour**

Default values that don't yet exist in the database should still be cached.

Two possible solutions:
1. Load default values into the database on every startup of the app - to make sure the values exist in the DB
2. Cache the default values as well, so we don't have to hit the db

**Comment by pjrobertson** [comment]
OK, never mind. I think this was because I was using a dummy cache.

**Comment by kunaldeo** [comment]
Thanks for the update.
