### ISSUE TITLE
missing app_label in models.Setting

### ISSUE THREAD

**Issue by evgenyfadeev** [kunaldeo/django-livesettings3#19]
Hello, I made a PR fixing this issue

https://github.com/kunaldeo/django-livesettings3/pull/18

Could you please merge and release an update if the above PR is acceptable? 

I've been getting this exception:

`RuntimeError: Model class livesettings.models.Setting doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

**Comment by kunaldeo** [comment]
Merged. Thank you for raising the PR.
