### ISSUE TITLE
The problem with django 1.10.1

### ISSUE THREAD

**Issue by recfunc** [kunaldeo/django-livesettings3#2]
I am getting error after added app.
`RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`
Django (1.10.1)
django-keyedcache3 (1.5.3)
django-livesettings3 (1.4.19)

**Comment by kunaldeo** [comment]
Please check your app settings as i am not able to recreate the issue.

**Comment by raamssundar** [comment]
Even I could not recreate the stated issue with Django 1.10.1
