### ISSUE TITLE
Can navigate to base template/settings

### ISSUE THREAD

**Issue by Kevin-Cain** [kunaldeo/django-livesettings3#28]
Hi There. I just upgraded to Django 4 from 2. There is an issue with the base template/route, where it will always default to a group, rather than hitting me main settings page. I believe its from the most recent version:

  -  ![image](https://github.com/kunaldeo/django-livesettings3/assets/79290152/64f22ee6-74ae-426c-bc97-764dbf634870)
  
 Should this be `if group and len(mgr.groups()) > 1:` ?

Thank you!

**Comment by Kevin-Cain** [comment]
I did end up using SuperGroup, which accomplishes what I needed. 

So now navigating to `/settings/` Defaults to one of my configuration groups, but they can still all be seen on that page.

**Comment by kunaldeo** [comment]
I am marking this closed as per last comment.
